#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PWCApp.Resource", IsApplication=true)]

namespace PWCApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int appbackground = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrowright = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int contacts = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int contactsxxl = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int CustomButton1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int newlogo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int powerweedcontrol = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int PWCIcon = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int actxtWorker = 2131034122;
			
			// aapt resource value: 0x7f050024
			public const int btnAssign = 2131034148;
			
			// aapt resource value: 0x7f05001d
			public const int btnBack = 2131034141;
			
			// aapt resource value: 0x7f050002
			public const int btnBackAJP2 = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int btnBackAJP3 = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int btnBackAJP4 = 2131034128;
			
			// aapt resource value: 0x7f050021
			public const int btnBackE = 2131034145;
			
			// aapt resource value: 0x7f050018
			public const int btnBackEE1 = 2131034136;
			
			// aapt resource value: 0x7f050028
			public const int btnBackVTP = 2131034152;
			
			// aapt resource value: 0x7f05001e
			public const int btnDelete = 2131034142;
			
			// aapt resource value: 0x7f050025
			public const int btnModEmployees = 2131034149;
			
			// aapt resource value: 0x7f05000e
			public const int btnNextAJP3 = 2131034126;
			
			// aapt resource value: 0x7f05001f
			public const int btnSave = 2131034143;
			
			// aapt resource value: 0x7f050011
			public const int btnSaveAJP4 = 2131034129;
			
			// aapt resource value: 0x7f050022
			public const int btnSaveEdited = 2131034146;
			
			// aapt resource value: 0x7f050005
			public const int btnSelectDate = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int btnSelectTime = 2131034118;
			
			// aapt resource value: 0x7f050012
			public const int btnSend = 2131034130;
			
			// aapt resource value: 0x7f050029
			public const int btnSendAll = 2131034153;
			
			// aapt resource value: 0x7f050026
			public const int btnViewPlan = 2131034150;
			
			// aapt resource value: 0x7f050023
			public const int imageView1 = 2131034147;
			
			// aapt resource value: 0x7f050019
			public const int ivContactPic = 2131034137;
			
			// aapt resource value: 0x7f050015
			public const int lblInfo = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int lblSubTitle = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int lblTitle = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout1 = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout2 = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout4 = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int lvCurrentWorkers = 2131034123;
			
			// aapt resource value: 0x7f050027
			public const int lvPlan = 2131034151;
			
			// aapt resource value: 0x7f050001
			public const int lvSelectJobs = 2131034113;
			
			// aapt resource value: 0x7f050017
			public const int lvWorkersEE1 = 2131034135;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int txtArea = 2131034120;
			
			// aapt resource value: 0x7f050016
			public const int txtEmployees = 2131034134;
			
			// aapt resource value: 0x7f05001c
			public const int txtHomePhone = 2131034140;
			
			// aapt resource value: 0x7f05000f
			public const int txtMessage = 2131034127;
			
			// aapt resource value: 0x7f05001b
			public const int txtMobileNo = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int txtName = 2131034138;
			
			// aapt resource value: 0x7f050020
			public const int txtNote = 2131034144;
			
			// aapt resource value: 0x7f050004
			public const int txtSelectedJob = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int txtTruckNumbers = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AssignJobP2 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AssignJobP3 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AssignJobP4 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CustomEmployees = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CustomRow = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EditEmployees1 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int EditEmployees2 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int EditPlanItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int list_item = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ViewTodaysPlan = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
